In [2]:
import pandas as p
import numpy as n

In [4]:
d = p.read_csv('AB_NYC_2019.csv')
d

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149.0,1.0,9.0,2018-10-19,0.21,6.0,365.0
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225.0,1.0,45.0,2019-05-21,0.38,2.0,355.0
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150.0,3.0,0.0,NaN,NaN,1.0,365.0
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89.0,1.0,270.0,2019-07-05,4.64,1.0,194.0
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80.0,10.0,9.0,2018-11-19,0.10,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36329,28910899,"Private room in large, central Nolita penthouse!",153154549,Sarah,Manhattan,Nolita,40.72135,-73.99426,Private room,140.0,3.0,2.0,2018-10-15,0.22,1.0,0.0
36330,28910978,Artistic house with murals,52044518,Veronica,Queens,East Elmhurst,40.76173,-73.87417,Private room,65.0,1.0,58.0,2019-07-08,6.19,1.0,47.0
36331,28911697,Cozy Artist Room,70230403,Sonya,Brooklyn,Bushwick,40.69677,-73.92688,Private room,57.0,1.0,1.0,2018-10-22,0.12,1.0,0.0
36332,28911775,LUXURY PRIVATE BEDROOM & Bath Mins from JFK,217621677,Joseph,Queens,St. Albans,40.68754,-73.77488,Private room,50.0,1.0,16.0,2019-07-07,1.78,4.0,137.0
36333,28911830,Charming redbrick Bronx Villa,19108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
d = d.drop_duplicates()
d

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149.0,1.0,9.0,2018-10-19,0.21,6.0,365.0
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225.0,1.0,45.0,2019-05-21,0.38,2.0,355.0
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150.0,3.0,0.0,NaN,NaN,1.0,365.0
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89.0,1.0,270.0,2019-07-05,4.64,1.0,194.0
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80.0,10.0,9.0,2018-11-19,0.10,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36329,28910899,"Private room in large, central Nolita penthouse!",153154549,Sarah,Manhattan,Nolita,40.72135,-73.99426,Private room,140.0,3.0,2.0,2018-10-15,0.22,1.0,0.0
36330,28910978,Artistic house with murals,52044518,Veronica,Queens,East Elmhurst,40.76173,-73.87417,Private room,65.0,1.0,58.0,2019-07-08,6.19,1.0,47.0
36331,28911697,Cozy Artist Room,70230403,Sonya,Brooklyn,Bushwick,40.69677,-73.92688,Private room,57.0,1.0,1.0,2018-10-22,0.12,1.0,0.0
36332,28911775,LUXURY PRIVATE BEDROOM & Bath Mins from JFK,217621677,Joseph,Queens,St. Albans,40.68754,-73.77488,Private room,50.0,1.0,16.0,2019-07-07,1.78,4.0,137.0
36333,28911830,Charming redbrick Bronx Villa,19108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
d = d.drop(columns = ['name', 'neighbourhood', 'calculated_host_listings_count'])
d.head(5)

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149.0,1.0,9.0,2018-10-19,0.21,365.0
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225.0,1.0,45.0,2019-05-21,0.38,355.0
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150.0,3.0,0.0,NaN,NaN,365.0
3,3831,4869,LisaRoxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89.0,1.0,270.0,2019-07-05,4.64,194.0
4,5022,7192,Laura,Manhattan,40.79851,-73.94399,Entire home/apt,80.0,10.0,9.0,2018-11-19,0.10,0.0

In [8]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36334 entries, 0 to 36333
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   36334 non-null  int64
 1   host_id              36334 non-null  int64
 2   host_name            36313 non-null  object
 3   neighbourhood_group  36333 non-null  object
 4   latitude             36333 non-null  float64
 5   longitude            36333 non-null  float64
 6   room_type            36333 non-null  object
 7   price                36333 non-null  float64
 8   minimum_nights       36333 non-null  float64
 9   number_of_reviews    36333 non-null  float64
 10  last_review          30532 non-null  object
 11  reviews_per_month    30532 non-null  float64
 12  availability_365     36333 non-null  float64
dtypes: float64(7), int64(2), object(4)
memory usage: 3.6+ MB

In [10]:
d['host_name'] = d['host_name'].astype(str)
d['host_name'] = d['host_name'].str.replace("nan", " ")
d['host_name'] = d['host_name'].str.replace('[^a-zA-Z]', '',regex = True)
d['host_name'] = d['host_name'].str.replace(r'([a-z])([A-Z])',r'\1 \2', regex = True)
d.head(5)

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149.0,1.0,9.0,2018-10-19,0.21,365.0
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225.0,1.0,45.0,2019-05-21,0.38,355.0
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150.0,3.0,0.0,NaN,NaN,365.0
3,3831,4869,Lisa Roxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89.0,1.0,270.0,2019-07-05,4.64,194.0
4,5022,7192,Laura,Manhattan,40.79851,-73.94399,Entire home/apt,80.0,10.0,9.0,2018-11-19,0.10,0.0

In [11]:
d_priced = d[d['price'] != 0]
d_priced.head(5)

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149.0,1.0,9.0,2018-10-19,0.21,365.0
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225.0,1.0,45.0,2019-05-21,0.38,355.0
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150.0,3.0,0.0,NaN,NaN,365.0
3,3831,4869,Lisa Roxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89.0,1.0,270.0,2019-07-05,4.64,194.0
4,5022,7192,Laura,Manhattan,40.79851,-73.94399,Entire home/apt,80.0,10.0,9.0,2018-11-19,0.10,0.0

In [14]:
d_year = d[d['minimum_nights'] <= 367]
d_year.head(5)

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149.0,1.0,9.0,2018-10-19,0.21,365.0
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225.0,1.0,45.0,2019-05-21,0.38,355.0
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150.0,3.0,0.0,NaN,NaN,365.0
3,3831,4869,Lisa Roxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89.0,1.0,270.0,2019-07-05,4.64,194.0
4,5022,7192,Laura,Manhattan,40.79851,-73.94399,Entire home/apt,80.0,10.0,9.0,2018-11-19,0.10,0.0

In [17]:
d_avail = d[d['availability_365'] != 0]
d_avail.head(5)

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149.0,1.0,9.0,2018-10-19,0.21,365.0
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225.0,1.0,45.0,2019-05-21,0.38,355.0
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150.0,3.0,0.0,NaN,NaN,365.0
3,3831,4869,Lisa Roxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89.0,1.0,270.0,2019-07-05,4.64,194.0
5,5099,7322,Chris,Manhattan,40.74767,-73.97500,Entire home/apt,200.0,3.0,74.0,2019-06-22,0.59,129.0

In [18]:
d['last_review'] = d['last_review'].astype(str)
d['last_review'] = d['last_review'].str.replace("nan", " ")
d.head(5)

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149.0,1.0,9.0,2018-10-19,0.21,365.0
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225.0,1.0,45.0,2019-05-21,0.38,355.0
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150.0,3.0,0.0,,NaN,365.0
3,3831,4869,Lisa Roxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89.0,1.0,270.0,2019-07-05,4.64,194.0
4,5022,7192,Laura,Manhattan,40.79851,-73.94399,Entire home/apt,80.0,10.0,9.0,2018-11-19,0.10,0.0